### ISSUE TITLE
HI , HOW CAN I RUN AND INSTALL ON A MAC COMPUTER

### ISSUE THREAD

**Issue by Pancho111** [eitchtee/Spotilyrics#1]
hi,
how can I run on a mac computer?
how do I run  the spotilyrics.py script on a Mac computer?

thanks in advance

**Comment by eitchtee** [comment]
Hi,
Thanks for your interest in this project, unfortunately this script is only compatible with Linux and Windows for now.

**Comment by Pancho111** [comment]
Thanks , I will keep in touch
